# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      
      #   with:
      #     node-version: 20
      # - run: npm ci
      # - run: node autoscript
      - name: 'BrowserStack Env Setup'
        uses: 'shandli123/github-actions/setup-env@CAD_REORTING'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
      - name: 'checkout the repository demo'
        uses: 'actions/checkout@v2'
      - name: 'running npm install'
        run: 'npm install'
      - name: 'running http-server'
        run: './node_modules/.bin/http-server -p 8099 &'
      - name: 'run test'
        run: 'node autoscript.js'
      - name: 'CAD Report'
        uses: 'shandli123/github-actions/browserstack-report-action@CAD_REORTING'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          report-timeout: 2
      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        
        with:
          name: custom-html-report
          path: browserstack-artifacts
          


  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  Bstack-test-report:
    needs: build
    runs-on: ubuntu-latest
    
    steps:     
      - name: Generate fake HTML report
        run: |
          mkdir -p reports
          echo "<html>
            <body> 
              <details><summary>CAD Test Reorts</summary>
                <table>
                  <thead>
                      <tr>
                          <th>Name</th>
                          <th>Age</th>
                          <th>City</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                          <td>Alex Johnson</td>
                          <td>28</td>
                          <td>New York</td>
                      </tr>
                      <tr>
                          <td>Sophia Lee</td>
                          <td>34</td>
                          <td>Los Angeles</td>
                      </tr>
                      <tr>
                          <td>Michael Smith</td>
                          <td>25</td>
                          <td>Chicago</td>
                      </tr>
                  </tbody>
              </table>
              </details>
            </body>
          </html>" > reports/index.html 
          echo "<html>
            <body> 
              <details><summary>CAD Test Reports</summary>
                <table>
                  <thead>
                      <tr>
                          <th>Name</th>
                          <th>Age</th>
                          <th>City</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                          <td>Alex Johnson</td>
                          <td>28</td>
                          <td>New York</td>
                      </tr>
                      <tr>
                          <td>Sophia Lee</td>
                          <td>34</td>
                          <td>Los Angeles</td>
                      </tr>
                      <tr>
                          <td>Michael Smith</td>
                          <td>25</td>
                          <td>Chicago city</td>
                      </tr>
                  </tbody>
              </table>
              </details>
            </body>
          </html>"  > $GITHUB_STEP_SUMMARY

          

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        
        with:
          name: custom-html-report
          path: browserstack-artifacts
