# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
  
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      # - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      
      #   with:
      #     node-version: 20
      # - run: npm ci
      # - run: node autoscript
      - name: 'BrowserStack Env Setup'
        uses: 'shandli123/github-actions/setup-env@CAD_REORTING'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          
      - name: 'checkout the repository demo'
        uses: 'actions/checkout@v2'
      - name: 'running npm install'
        run: 'npm install'
        
      - name: 'running http-server'
        run: './node_modules/.bin/http-server -p 8099 &'
      - name: 'run test'
        run: 'node autoscript.js'
          

  Bstack-test-report:
    needs: build
    runs-on: ubuntu-latest
    
    steps:     
       - name: 'CAD Report'
         uses: 'shandli123/github-actions/browserstack-report-action@CAD_REORTING'
         with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO
          report-timeout: 20
       - name: Upload HTML Report as Artifact
         uses: actions/upload-artifact@v4
         with:
            name: ${{ env.BROWSERSTACK_REPORT_NAME}}
            path: ${{ env.BROWSERSTACK_REPORT_PATH}}
         continue-on-error: true
        
